#!/usr/bin/env python3
"""
Rubisco Visualization Utility: GIF Creator

This script scans the output directory for folders containing PNG frames
(generated by the main analysis script) and stitches them into animated GIF files.

Usage:
    python create_gifs.py -o /path/to/analysis/output
"""

import argparse
import logging
import re
import sys
from pathlib import Path

# External dependency for GIF creation
import imageio.v3 as iio

# ------------------------
# DEFAULT PATH CONFIG
# ------------------------
DEFAULT_OUTPUT_DIR = Path(
    "/Users/jb1725/Documents/York/PDRA/Manuscripts/"
    "Gaurav Sticker Number/LAMMPs/chlamy"
)

# DEFAULT_OUTPUT_DIR = Path(
#     "/Users/jb1725/Documents/York/PDRA/Manuscripts/"
#     "Gaurav Sticker Number/LAMMPs/chlorella"
# )

DEFAULT_FPS = 30  # Frames Per Second for the output GIF

# -----------------------------------------------------------------------------
# LOGGING SETUP
# -----------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)


# -----------------------------------------------------------------------------
# UTILITY FUNCTIONS
# -----------------------------------------------------------------------------

def parse_args():
    """Parse command line arguments."""
    p = argparse.ArgumentParser(description="Stitch PNG frames into GIFs")
    p.add_argument("-o", "--output_dir", type=str, default=str(DEFAULT_OUTPUT_DIR),
                   help="Directory containing frame folders (ends in _gif_frames)")
    p.add_argument("--fps", type=int, default=DEFAULT_FPS,
                   help="Frames per second for the output GIF")
    return p.parse_args()


def create_gif_from_frames(frames_dir: Path, output_dir: Path, filename: str, fps=10):
    """
    Stitches saved PNG frames from a directory into a single animated GIF.

    Args:
        frames_dir (Path): Directory containing the source PNGs.
        output_dir (Path): Directory to save the result.
        filename (str): Name of the output GIF file.
        fps (int): Speed of animation (frames per second).
    """
    if not frames_dir.exists():
        logging.warning("Frame directory not found: %s", frames_dir)
        return

    logging.info("Processing frames from: %s", frames_dir.name)

    # 1. Collect all PNG files
    # We use a regex sort key to ensure 'frame_10.png' comes after 'frame_2.png'
    # (numerical sorting) rather than alphabetical ('10' before '2').
    files = list(frames_dir.glob("frame_*.png"))

    if not files:
        logging.warning("  No 'frame_*.png' files found in %s", frames_dir.name)
        return

    # Sort files numerically based on the frame number in the filename
    try:
        files.sort(key=lambda x: int(re.search(r'_(\d+)\.png$', x.name).group(1)))
    except AttributeError:
        logging.warning("  Could not determine frame numbers from filenames. using default sort.")
        files.sort()

    output_path = output_dir / filename

    try:
        # 2. Read images into memory
        # Note: For very large sets (1000+ frames), this might need batching,
        # but for ~200 frames, loading into a list is fine.
        images = [iio.imread(f) for f in files]

        # 3. Write GIF
        # duration is in milliseconds per frame (1000ms / fps)
        # loop=0 means loop infinitely
        iio.imwrite(
            output_path,
            images,
            duration=1000 / fps,
            loop=0
        )
        logging.info("  Success! Saved GIF to: %s", output_path.name)

    except Exception as e:
        logging.error("  Failed to create GIF for %s: %s", frames_dir.name, e)


# -----------------------------------------------------------------------------
# MAIN EXECUTION
# -----------------------------------------------------------------------------

def main():
    args = parse_args()
    output_dir = Path(args.output_dir)

    if not output_dir.exists():
        logging.error("Output directory does not exist: %s", output_dir)
        return

    logging.info("Scanning for frame directories in: %s", output_dir)

    # Find all subdirectories ending in '_gif_frames'
    frame_dirs = list(output_dir.glob("*_gif_frames"))

    if not frame_dirs:
        logging.warning("No frame directories found. Run the analysis script first.")
        return

    count = 0
    for frames_dir in frame_dirs:
        if not frames_dir.is_dir():
            continue

        # Construct output filename:
        # e.g., "9rbm_1_5_gif_frames" -> "9rbm_1_5_animation.gif"
        rbm_ratio_name = frames_dir.name.replace("_gif_frames", "")
        gif_name = f"{rbm_ratio_name}_animation.gif"

        create_gif_from_frames(
            frames_dir,
            output_dir,
            gif_name,
            fps=args.fps
        )
        count += 1

    logging.info("Done. Created %d GIFs.", count)


if __name__ == "__main__":
    main()